/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArtifactsRouteImport } from './routes/artifacts'
import { Route as BillingRouteImport } from './routes/billing'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SourcesRouteImport } from './routes/sources'
import { Route as TransformRouteImport } from './routes/transform'
import { Route as ArtifactsIndexRouteImport } from './routes/artifacts.index'
import { Route as ArtifactsIdRouteImport } from './routes/artifacts.$id'
import { Route as ProjectsIndexRouteImport } from './routes/projects.index'
import { Route as ProjectsIdRouteImport } from './routes/projects.$id'
import { Route as SourcesIndexRouteImport } from './routes/sources.index'
import { Route as SourcesIdRouteImport } from './routes/sources.$id'
import { Route as TransformIndexRouteImport } from './routes/transform.index'
import { Route as TransformIdRouteImport } from './routes/transform.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtifactsRoute = ArtifactsRouteImport.update({
  id: '/artifacts',
  path: '/artifacts',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingRoute = BillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SourcesRoute = SourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => rootRouteImport,
} as any)
const TransformRoute = TransformRouteImport.update({
  id: '/transform',
  path: '/transform',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtifactsIndexRoute = ArtifactsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ArtifactsRoute,
} as any)
const ArtifactsIdRoute = ArtifactsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ArtifactsRoute,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectsRoute,
} as any)
const ProjectsIdRoute = ProjectsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ProjectsRoute,
} as any)
const SourcesIndexRoute = SourcesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SourcesRoute,
} as any)
const SourcesIdRoute = SourcesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => SourcesRoute,
} as any)
const TransformIndexRoute = TransformIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TransformRoute,
} as any)
const TransformIdRoute = TransformIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => TransformRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/artifacts': typeof ArtifactsRouteWithChildren
  '/billing': typeof BillingRoute
  '/dashboard': typeof DashboardRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/sources': typeof SourcesRouteWithChildren
  '/transform': typeof TransformRouteWithChildren
  '/artifacts/$id': typeof ArtifactsIdRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/sources/$id': typeof SourcesIdRoute
  '/transform/$id': typeof TransformIdRoute
  '/artifacts/': typeof ArtifactsIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/sources/': typeof SourcesIndexRoute
  '/transform/': typeof TransformIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/billing': typeof BillingRoute
  '/dashboard': typeof DashboardRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/artifacts/$id': typeof ArtifactsIdRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/sources/$id': typeof SourcesIdRoute
  '/transform/$id': typeof TransformIdRoute
  '/artifacts': typeof ArtifactsIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/sources': typeof SourcesIndexRoute
  '/transform': typeof TransformIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/artifacts': typeof ArtifactsRouteWithChildren
  '/billing': typeof BillingRoute
  '/dashboard': typeof DashboardRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/sources': typeof SourcesRouteWithChildren
  '/transform': typeof TransformRouteWithChildren
  '/artifacts/$id': typeof ArtifactsIdRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/sources/$id': typeof SourcesIdRoute
  '/transform/$id': typeof TransformIdRoute
  '/artifacts/': typeof ArtifactsIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/sources/': typeof SourcesIndexRoute
  '/transform/': typeof TransformIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/artifacts'
    | '/billing'
    | '/dashboard'
    | '/history'
    | '/login'
    | '/pricing'
    | '/projects'
    | '/settings'
    | '/signup'
    | '/sources'
    | '/transform'
    | '/artifacts/$id'
    | '/projects/$id'
    | '/sources/$id'
    | '/transform/$id'
    | '/artifacts/'
    | '/projects/'
    | '/sources/'
    | '/transform/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/billing'
    | '/dashboard'
    | '/history'
    | '/login'
    | '/pricing'
    | '/settings'
    | '/signup'
    | '/artifacts/$id'
    | '/projects/$id'
    | '/sources/$id'
    | '/transform/$id'
    | '/artifacts'
    | '/projects'
    | '/sources'
    | '/transform'
  id:
    | '__root__'
    | '/'
    | '/artifacts'
    | '/billing'
    | '/dashboard'
    | '/history'
    | '/login'
    | '/pricing'
    | '/projects'
    | '/settings'
    | '/signup'
    | '/sources'
    | '/transform'
    | '/artifacts/$id'
    | '/projects/$id'
    | '/sources/$id'
    | '/transform/$id'
    | '/artifacts/'
    | '/projects/'
    | '/sources/'
    | '/transform/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArtifactsRoute: typeof ArtifactsRouteWithChildren
  BillingRoute: typeof BillingRoute
  DashboardRoute: typeof DashboardRoute
  HistoryRoute: typeof HistoryRoute
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  ProjectsRoute: typeof ProjectsRouteWithChildren
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  SourcesRoute: typeof SourcesRouteWithChildren
  TransformRoute: typeof TransformRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artifacts': {
      id: '/artifacts'
      path: '/artifacts'
      fullPath: '/artifacts'
      preLoaderRoute: typeof ArtifactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing': {
      id: '/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof BillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sources': {
      id: '/sources'
      path: '/sources'
      fullPath: '/sources'
      preLoaderRoute: typeof SourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transform': {
      id: '/transform'
      path: '/transform'
      fullPath: '/transform'
      preLoaderRoute: typeof TransformRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artifacts/': {
      id: '/artifacts/'
      path: '/'
      fullPath: '/artifacts/'
      preLoaderRoute: typeof ArtifactsIndexRouteImport
      parentRoute: typeof ArtifactsRoute
    }
    '/artifacts/$id': {
      id: '/artifacts/$id'
      path: '/$id'
      fullPath: '/artifacts/$id'
      preLoaderRoute: typeof ArtifactsIdRouteImport
      parentRoute: typeof ArtifactsRoute
    }
    '/projects/': {
      id: '/projects/'
      path: '/'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/projects/$id': {
      id: '/projects/$id'
      path: '/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof ProjectsIdRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/sources/': {
      id: '/sources/'
      path: '/'
      fullPath: '/sources/'
      preLoaderRoute: typeof SourcesIndexRouteImport
      parentRoute: typeof SourcesRoute
    }
    '/sources/$id': {
      id: '/sources/$id'
      path: '/$id'
      fullPath: '/sources/$id'
      preLoaderRoute: typeof SourcesIdRouteImport
      parentRoute: typeof SourcesRoute
    }
    '/transform/': {
      id: '/transform/'
      path: '/'
      fullPath: '/transform/'
      preLoaderRoute: typeof TransformIndexRouteImport
      parentRoute: typeof TransformRoute
    }
    '/transform/$id': {
      id: '/transform/$id'
      path: '/$id'
      fullPath: '/transform/$id'
      preLoaderRoute: typeof TransformIdRouteImport
      parentRoute: typeof TransformRoute
    }
  }
}

interface ArtifactsRouteChildren {
  ArtifactsIdRoute: typeof ArtifactsIdRoute
  ArtifactsIndexRoute: typeof ArtifactsIndexRoute
}

const ArtifactsRouteChildren: ArtifactsRouteChildren = {
  ArtifactsIdRoute: ArtifactsIdRoute,
  ArtifactsIndexRoute: ArtifactsIndexRoute,
}

const ArtifactsRouteWithChildren = ArtifactsRoute._addFileChildren(
  ArtifactsRouteChildren,
)

interface ProjectsRouteChildren {
  ProjectsIdRoute: typeof ProjectsIdRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsIdRoute: ProjectsIdRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

interface SourcesRouteChildren {
  SourcesIdRoute: typeof SourcesIdRoute
  SourcesIndexRoute: typeof SourcesIndexRoute
}

const SourcesRouteChildren: SourcesRouteChildren = {
  SourcesIdRoute: SourcesIdRoute,
  SourcesIndexRoute: SourcesIndexRoute,
}

const SourcesRouteWithChildren =
  SourcesRoute._addFileChildren(SourcesRouteChildren)

interface TransformRouteChildren {
  TransformIdRoute: typeof TransformIdRoute
  TransformIndexRoute: typeof TransformIndexRoute
}

const TransformRouteChildren: TransformRouteChildren = {
  TransformIdRoute: TransformIdRoute,
  TransformIndexRoute: TransformIndexRoute,
}

const TransformRouteWithChildren = TransformRoute._addFileChildren(
  TransformRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArtifactsRoute: ArtifactsRouteWithChildren,
  BillingRoute: BillingRoute,
  DashboardRoute: DashboardRoute,
  HistoryRoute: HistoryRoute,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  ProjectsRoute: ProjectsRouteWithChildren,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  SourcesRoute: SourcesRouteWithChildren,
  TransformRoute: TransformRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
